from .state import init_session_state
from .consent import render_consent_screen
from .tab_income import render_tab_income
from .tab_retirement import render_tab_retirement
from .tab_budget import render_tab_budget
from .tab_quiz import render_tab_quiz
from .tab_action import render_tab_action
from .tab_feedback import render_tab_feedback
from .tab_plan import render_tab_plan
from .tab_rent_vs_buy import render_tab_rent_vs_buy
